apiVersion: mage-common.randomvariable.co.uk/v1alpha1
kind: ToolConfiguration
spec:
  toolsDir: hack/bin
  tools:
    - name: golangci-lint
      version: v2.9.0
      sources:
        - type: golangci-lint
          url: github.com/golangci/golangci-lint/v2/cmd/golangci-lint

    - name: helm
      version: v4.1.1
      sources:
        - type: download
          url: "https://get.helm.sh/helm-{{.Version}}-{{.OS}}-{{.Arch}}.tar.gz"
          binaryPath: "{{.OS}}-{{.Arch}}/helm"
          checksum:
            url: "https://get.helm.sh/helm-{{.Version}}-{{.OS}}-{{.Arch}}.tar.gz.sha256sum"

    - name: tilt
      version: "0.36.3"
      sources:
        - type: download
          url: "https://github.com/tilt-dev/tilt/releases/download/v{{.Version}}/tilt.{{.Version}}.{{.OS}}.{{.Arch}}.tar.gz"
          binaryPath: tilt
          osMap:
            darwin: mac
          archMap:
            amd64: x86_64
          checksum:
            url: "https://github.com/tilt-dev/tilt/releases/download/v{{.Version}}/checksums.txt"

    - name: kubectl
      version: v1.35.1
      sources:
        - type: download
          url: "https://dl.k8s.io/release/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl"
          checksum:
            url: "https://dl.k8s.io/release/{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl.sha256"

    - name: k3d
      version: v5.8.3
      sources:
        - type: download
          url: "https://github.com/k3d-io/k3d/releases/download/{{.Version}}/k3d-{{.OS}}-{{.Arch}}"
          checksum:
            url: "https://github.com/k3d-io/k3d/releases/download/{{.Version}}/checksums.txt"

    - name: kind
      version: v0.31.0
      sources:
        - type: download
          url: "https://github.com/kubernetes-sigs/kind/releases/download/{{.Version}}/kind-{{.OS}}-{{.Arch}}"
          checksum:
            url: "https://github.com/kubernetes-sigs/kind/releases/download/{{.Version}}/kind-{{.OS}}-{{.Arch}}.sha256sum"

    - name: buildifier
      version: v0.0.0-20260211083412-859bfffeef82
      sources:
        - type: go
          url: github.com/bazelbuild/buildtools/buildifier
